name: Test PR
'on': pull_request

jobs:
  install-and-test:
    name: ğŸ› ï¸ Install & Test
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ—œï¸ Checkout
        uses: actions/checkout@v6

      - name: ğŸ—œï¸ Setup node version
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: ğŸ› ï¸ Install
        uses: ./.github/actions/cached-deps

      - name: ğŸ› ï¸ Sync versions
        run: yarn script:sync-projects

      - name: ğŸ› ï¸ Find PR
        uses: jwalton/gh-find-current-pr@v1
        id: findPr

      - name: ğŸ§¹ Lint
        run: yarn lint

      - name: â™»ï¸ Check circular dependencies
        run: yarn check-circular-dependencies

      - name: ğŸ§ª Run tests (ngx-fixed-footer)
        run: yarn test ngx-fixed-footer --coverage

      - name: ğŸ§ª Run tests (demo)
        run: yarn test demo --coverage

      - name: ğŸ§ª Report code coverage
        uses: ./.github/actions/report-pr
        with:
          coverage-file: coverage/**/cobertura-coverage.xml

      - name: â¬†ï¸ Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
          dry_run: true

      - name: ğŸ“¦ Build demo app
        run: yarn build:demo --base-href https://celtian.github.io/ngx-fixed-footer/

      - name: ğŸ“¦ Build ngx-fixed-footer
        run: yarn build
